### ISSUE TITLE
ext_resource type="Animation" not saved?

### ISSUE THREAD

**Issue by rakkarage** [KoBeWi/Godot-Frame-Converter#1]
I have all my animations saved as files (ext_resource). Conversion works great in editor but the animation files are not saved so I would have to select and save xx files.  Boohoo. Still great cuz they are converted but maybe there is a way to save or flag the files as dirty so they are automatically saved? Or maybe a godot bug...

I tried using `ResourceSaver.save(new_path, animation)` but not work idk

here are some frame animations in external format for testing
https://github.com/rakkarage/PixelMob

Thanks!

**Comment by KoBeWi** [comment]
Hey, sorry for late reply, this got flooded by other notifications and I forgot to check it again.
I added a new commit that automatically saves converted animation if it's stored in external file: 71b0d855b12e6aca7f5bfdf47d0b3ddff2d5d029 That resolves your issue.
